// <auto-generated />
using System;
using DataStore.SQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebApp.Migrations.SqlServerMigrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220517233636_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CoreBusiness.Entities.Brand", b =>
                {
                    b.Property<Guid>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrandId");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            BrandId = new Guid("d478d6e1-64ea-4f63-a635-96f176c560cc"),
                            Name = "Trek"
                        },
                        new
                        {
                            BrandId = new Guid("92f6361a-04ed-4bde-a4ac-84aba9b1f7ca"),
                            Name = "Connondale"
                        });
                });

            modelBuilder.Entity("CoreBusiness.Entities.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("60d70416-906c-4c1c-8f5e-a0183bf6cada"),
                            Description = "This bike is designed with excellent braking systems and shock-absorbing features that can easily handle serious bumps, rocks, dirt trails, roots and ruts.",
                            Name = "Mountain Bike"
                        },
                        new
                        {
                            CategoryId = new Guid("e3980339-1e2e-49b2-acd4-bc80d245e446"),
                            Description = "Road bikes are best identified by their drop or turned-down handlebars and skinny tires.",
                            Name = "Road Bike"
                        },
                        new
                        {
                            CategoryId = new Guid("0bfb6c1a-af0c-4a14-848f-f6912a10e2ab"),
                            Description = "These bikes include an electric motor which you can charge by plugging it into a regular outlet.  When you peddle, the electric motor provides an assist so that you go faster and hills are made easier.",
                            Name = "Electric Bike"
                        });
                });

            modelBuilder.Entity("CoreBusiness.Entities.Comment", b =>
                {
                    b.Property<Guid>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CustomerId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProductId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CommentId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            CommentId = new Guid("eab0705f-b01b-4aaa-9afd-54a5f0d4491e"),
                            CustomerId = new Guid("d6b855eb-231c-4ea1-8285-2b9ccaffe275"),
                            ProductComment = "I had a really good experience here, I ordered some parts from the online site. They were at a great price and it said 4 - 8 days for delivery which was longer than I would have liked but for the price I couldn't complain. The parts arrived the next day and were well packaged and as described! What more could you ask for!",
                            ProductId = new Guid("3645bfdf-16e7-42a4-abdb-cc38c770eb8a")
                        },
                        new
                        {
                            CommentId = new Guid("19e3f536-a607-4f49-9cc1-b3929a1c24d2"),
                            CustomerId = new Guid("d6b855eb-231c-4ea1-8285-2b9ccaffe275"),
                            ProductComment = "I got a trek mountain track steel framed bike three years ago and put a 49cc 4 stoke motor on it. I did modify the brakes and put a oil shock front fork on it and it's held up awesome, no cracks or weak spots. All my friends have had to reinforce their bikes in less time than I've had mine. I could not ask for better.. ABSOLUTELY LOVE MY TREK !!!!!!!!!",
                            ProductId = new Guid("3a8e9167-a66a-4b19-88f7-8c6ed0821229")
                        },
                        new
                        {
                            CommentId = new Guid("e7f4fe96-6c87-4769-ac53-bdb08867cfbe"),
                            CustomerId = new Guid("3a6437c3-5dc9-4321-9d48-a753e90e2d5a"),
                            ProductComment = "My order went wrong however I was extremely happy with how Will dealt with my issue and I wouldn't hesitate to place another order. ",
                            ProductId = new Guid("3645bfdf-16e7-42a4-abdb-cc38c770eb8a")
                        },
                        new
                        {
                            CommentId = new Guid("3786ab8a-40dd-4013-8c62-ebe670d8a4ca"),
                            CustomerId = new Guid("3a6437c3-5dc9-4321-9d48-a753e90e2d5a"),
                            ProductComment = "For most of the bikes I test, I feel like they excel at either climbing or descending. However, the Cannondale Trail 6 really shines as a mellow all-rounder… it lands comfortably in the middle as a true generalist.",
                            ProductId = new Guid("a3921483-a45e-4cb7-846d-7c28446bf7a6")
                        },
                        new
                        {
                            CommentId = new Guid("fbaaf426-db46-4fcb-bbff-52b3d16bcd28"),
                            CustomerId = new Guid("d6b855eb-231c-4ea1-8285-2b9ccaffe275"),
                            ProductComment = "The Trail 1 is a bike that seems like an excellent choice on which to gain experience… The intermediate step between a beginner’s bike and a more expensive, expert model.",
                            ProductId = new Guid("70fb6660-0bba-428d-a5a7-814eb3b3bf47")
                        },
                        new
                        {
                            CommentId = new Guid("f215ddb7-09eb-4a86-81c2-68a51bd59cec"),
                            CustomerId = new Guid("3a6437c3-5dc9-4321-9d48-a753e90e2d5a"),
                            ProductComment = "Smartform aluminium frame is one of the most comfortable here… Stand-over clearance is at a premium …seat tube is way too tall… Cannondale… if you’re a heavy rider this fork may just be too quick.",
                            ProductId = new Guid("70fb6660-0bba-428d-a5a7-814eb3b3bf47")
                        },
                        new
                        {
                            CommentId = new Guid("ad76f53b-2679-4eda-88e2-98720815839e"),
                            CustomerId = new Guid("3a6437c3-5dc9-4321-9d48-a753e90e2d5a"),
                            ProductComment = "I purchased this bike to use as a commuter bike… to be capable enough to ride MTB trails… after putting 200mi on it in the three months that I’ve owned it, I can say with confidence that this bike fits the bill.",
                            ProductId = new Guid("405e657d-68f9-4c66-8a91-b7baffb20eaf")
                        },
                        new
                        {
                            CommentId = new Guid("54bd18c7-3668-405a-89fe-5e97020d6b3c"),
                            CustomerId = new Guid("3a6437c3-5dc9-4321-9d48-a753e90e2d5a"),
                            ProductComment = "For this price, you do get hydros… It’s an SLX shifter. This works so smooth… The bike itself is really light.",
                            ProductId = new Guid("3645bfdf-16e7-42a4-abdb-cc38c770eb8a")
                        });
                });

            modelBuilder.Entity("CoreBusiness.Entities.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = new Guid("d6b855eb-231c-4ea1-8285-2b9ccaffe275"),
                            City = "Izmir",
                            District = "Buca",
                            Name = "Eray Berberoglu",
                            Street = "206/5"
                        },
                        new
                        {
                            CustomerId = new Guid("3a6437c3-5dc9-4321-9d48-a753e90e2d5a"),
                            City = "Ankara",
                            District = "Cankaya",
                            Name = "Hakan Bisikletman",
                            Street = "Sezginler Street"
                        });
                });

            modelBuilder.Entity("CoreBusiness.Entities.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = new Guid("5e589759-dc33-4979-ab6b-5edc93a6ba29"),
                            CustomerId = new Guid("d6b855eb-231c-4ea1-8285-2b9ccaffe275"),
                            OrderDate = new DateTime(2022, 3, 1, 7, 22, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            OrderId = new Guid("db88ba95-54a5-4094-9ade-2402654b7c95"),
                            CustomerId = new Guid("3a6437c3-5dc9-4321-9d48-a753e90e2d5a"),
                            OrderDate = new DateTime(2021, 8, 11, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            OrderId = new Guid("ddb45744-e12e-49b2-a428-718d082f88f1"),
                            CustomerId = new Guid("d6b855eb-231c-4ea1-8285-2b9ccaffe275"),
                            OrderDate = new DateTime(2008, 5, 24, 3, 21, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CoreBusiness.Entities.OrderItems", b =>
                {
                    b.Property<Guid>("OrderItemsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderItemsId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            OrderItemsId = new Guid("e901026d-a174-4f3f-9efd-542c2bb620c5"),
                            OrderId = new Guid("5e589759-dc33-4979-ab6b-5edc93a6ba29"),
                            ProductId = new Guid("3645bfdf-16e7-42a4-abdb-cc38c770eb8a"),
                            Quantity = 3
                        },
                        new
                        {
                            OrderItemsId = new Guid("be250e81-d0c2-4379-9c8a-d9f0336404ed"),
                            OrderId = new Guid("5e589759-dc33-4979-ab6b-5edc93a6ba29"),
                            ProductId = new Guid("3a8e9167-a66a-4b19-88f7-8c6ed0821229"),
                            Quantity = 2
                        },
                        new
                        {
                            OrderItemsId = new Guid("ffd9e796-d416-4ab7-8ef2-9957957a5f0d"),
                            OrderId = new Guid("5e589759-dc33-4979-ab6b-5edc93a6ba29"),
                            ProductId = new Guid("3645bfdf-16e7-42a4-abdb-cc38c770eb8a"),
                            Quantity = 1
                        },
                        new
                        {
                            OrderItemsId = new Guid("95c21140-b58d-44a5-8d3b-214a90e59b7d"),
                            OrderId = new Guid("5e589759-dc33-4979-ab6b-5edc93a6ba29"),
                            ProductId = new Guid("a3921483-a45e-4cb7-846d-7c28446bf7a6"),
                            Quantity = 5
                        },
                        new
                        {
                            OrderItemsId = new Guid("61c9ace3-9225-4559-b541-45fe7d5f73d8"),
                            OrderId = new Guid("db88ba95-54a5-4094-9ade-2402654b7c95"),
                            ProductId = new Guid("70fb6660-0bba-428d-a5a7-814eb3b3bf47"),
                            Quantity = 2
                        },
                        new
                        {
                            OrderItemsId = new Guid("5da55686-5ef1-4906-851e-b206b748f320"),
                            OrderId = new Guid("db88ba95-54a5-4094-9ade-2402654b7c95"),
                            ProductId = new Guid("405e657d-68f9-4c66-8a91-b7baffb20eaf"),
                            Quantity = 7
                        },
                        new
                        {
                            OrderItemsId = new Guid("ee68e4bf-ce6a-4a8a-beb6-7ca35476547a"),
                            OrderId = new Guid("ddb45744-e12e-49b2-a428-718d082f88f1"),
                            ProductId = new Guid("405e657d-68f9-4c66-8a91-b7baffb20eaf"),
                            Quantity = 1
                        },
                        new
                        {
                            OrderItemsId = new Guid("2eee2316-a6a7-4cbc-b716-f88197513cbf"),
                            OrderId = new Guid("ddb45744-e12e-49b2-a428-718d082f88f1"),
                            ProductId = new Guid("70fb6660-0bba-428d-a5a7-814eb3b3bf47"),
                            Quantity = 6
                        },
                        new
                        {
                            OrderItemsId = new Guid("e304535a-5e65-4ec8-80de-adeeadaf55c9"),
                            OrderId = new Guid("ddb45744-e12e-49b2-a428-718d082f88f1"),
                            ProductId = new Guid("3645bfdf-16e7-42a4-abdb-cc38c770eb8a"),
                            Quantity = 4
                        });
                });

            modelBuilder.Entity("CoreBusiness.Entities.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BrandId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModelYear")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Price")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<int?>("Quantity")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("3645bfdf-16e7-42a4-abdb-cc38c770eb8a"),
                            BrandId = new Guid("d478d6e1-64ea-4f63-a635-96f176c560cc"),
                            CategoryId = new Guid("60d70416-906c-4c1c-8f5e-a0183bf6cada"),
                            Color = "Marigold to Red Fade",
                            ModelYear = 2015,
                            Name = "Rail 9.9 XX1 AXS",
                            Price = 13799.99,
                            Quantity = 100,
                            Size = "L"
                        },
                        new
                        {
                            ProductId = new Guid("3a8e9167-a66a-4b19-88f7-8c6ed0821229"),
                            BrandId = new Guid("d478d6e1-64ea-4f63-a635-96f176c560cc"),
                            CategoryId = new Guid("60d70416-906c-4c1c-8f5e-a0183bf6cada"),
                            Color = "Carbon Red",
                            ModelYear = 2022,
                            Name = "Rail 9.8 XT",
                            Price = 9199.9899999999998,
                            Quantity = 200,
                            Size = "M"
                        },
                        new
                        {
                            ProductId = new Guid("a3921483-a45e-4cb7-846d-7c28446bf7a6"),
                            BrandId = new Guid("92f6361a-04ed-4bde-a4ac-84aba9b1f7ca"),
                            CategoryId = new Guid("e3980339-1e2e-49b2-acd4-bc80d245e446"),
                            Color = "Candy Red",
                            ModelYear = 2020,
                            Name = "CAAD Optimo",
                            Price = 23213.0,
                            Quantity = 300,
                            Size = "S"
                        },
                        new
                        {
                            ProductId = new Guid("70fb6660-0bba-428d-a5a7-814eb3b3bf47"),
                            BrandId = new Guid("92f6361a-04ed-4bde-a4ac-84aba9b1f7ca"),
                            CategoryId = new Guid("e3980339-1e2e-49b2-acd4-bc80d245e446"),
                            Color = "Stealth Grey",
                            ModelYear = 2018,
                            Name = "CAAD13 Disc 105",
                            Price = 18529.990000000002,
                            Quantity = 300,
                            Size = "XS"
                        },
                        new
                        {
                            ProductId = new Guid("405e657d-68f9-4c66-8a91-b7baffb20eaf"),
                            BrandId = new Guid("d478d6e1-64ea-4f63-a635-96f176c560cc"),
                            CategoryId = new Guid("0bfb6c1a-af0c-4a14-848f-f6912a10e2ab"),
                            Color = "Gloss Alpine Navy Smoke",
                            ModelYear = 2021,
                            Name = "E-Caliber 9.9 XTR",
                            Price = 12549.99,
                            Quantity = 300,
                            Size = "XL"
                        });
                });

            modelBuilder.Entity("CoreBusiness.Entities.Comment", b =>
                {
                    b.HasOne("CoreBusiness.Entities.Customer", "Customer")
                        .WithMany("Comments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreBusiness.Entities.Product", "Product")
                        .WithMany("Comments")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CoreBusiness.Entities.Order", b =>
                {
                    b.HasOne("CoreBusiness.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CoreBusiness.Entities.OrderItems", b =>
                {
                    b.HasOne("CoreBusiness.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreBusiness.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CoreBusiness.Entities.Product", b =>
                {
                    b.HasOne("CoreBusiness.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreBusiness.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CoreBusiness.Entities.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CoreBusiness.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CoreBusiness.Entities.Customer", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CoreBusiness.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("CoreBusiness.Entities.Product", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
